Add user auth and UI
UtsavK55/Event-management-mobile-app pull request #3
Opened 2024-10-14 07:50 UTC by UtsavK55

Add user authentication and Auth pages UI

2024-10-14 09:33 UTC, adiTrivsme requested changes

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/button/styles.ts
> +    backgroundColor: '#4169E1',
define and use all colors from the theme

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/footer/Footer.tsx
> +}: AlreadySignedUpProps) => {
`AlreadySignedUpProps`??

I assume this footer is used in both login and signup, right?

also name of the component is not correct, it should signify its being used on Auth screens, its not like this footer will be used everywhere in the app

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/input/styles.ts
> +    backgroundColor: '#D9D9D9',
move colors to the theme

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/loginForm/Loginform.tsx
> +          email: {value: curInputs.email.value, isValid: emailIsValid},
use spread operator to override

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/radioButton/RadioButton.tsx
> +      <Text style={styles.label}>{label}*</Text>
only add `*` when the radio field is required, make this customizable

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/signUpForm/SignUpForm.tsx
> +import {styles} from './styles';
keep similar import together - move `styles` to the bottom of imports

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/signUpForm/SignUpForm.tsx
> +import RadioButton from '@src/components/radioButton';
instead of `@src`, define alias such as `@components`, `@storage`, `@contexts`, etc.

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/signUpForm/SignUpForm.tsx
> +    setLoginId(signupData.id);
where are you resetting form fields??

2024-10-14 09:33 UTC, adiTrivsme commented on src/components/signUpForm/SignUpForm.tsx
> +      <Image style={styles.image} source={require('../../assets/logo.png')} />
never require anything inline, require this image outside the component and use here

2024-10-14 09:33 UTC, adiTrivsme commented on src/contexts/isLoggedInContext.tsx
The name of the file does not seem right

2024-10-14 09:33 UTC, adiTrivsme commented on src/navigation/AuthNavigator.tsx
> +import Login from '@src/screens/login/Login';
define `@screens`

2024-10-14 09:33 UTC, adiTrivsme commented on src/navigation/Navigator.tsx
> +  useEffect(() => {
line breaks

2024-10-14 09:33 UTC, adiTrivsme commented on src/storage/storage.ts
> +export const storeData = async (value: SignupInfoArr | string, key: string) => {
this is not going to be used only for `signup`, update its type

2024-10-14 09:33 UTC, adiTrivsme commented on src/types/navigation.d.ts
> +type SignupScreenProps = NativeStackScreenProps<
use `prettier`

2024-10-14 10:09 UTC, 02priyanshi requested changes

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/baseContainer/BaseContainer.tsx
import order is not correct

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/input/Input.tsx
as discussed value, onChangeText, placeholder should be mandatory fields and define same in TextInput and get these props seperately in props and use same in textinput

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/input/styles.ts
>      color: 'red',
move colors to the theme

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/loginForm/Loginform.tsx
> +      setInputs(curInputs => {
why curInputs still there? already told you to use proper naming convention

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/loginForm/Loginform.tsx
> +      storeData(userData.id, 'isLoggedIn');
create a constant file for storage keys

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/loginForm/Loginform.tsx
> +        <Button mode="default" onPress={handleSubmit}>
no need to wrap button text inside Button instead of this pass title props for button name and use that in button comp

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/loginForm/styles.ts
> +    height: 100,
use % or window height width to adjust image size

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/radioButton/styles.ts
> +    backgroundColor: '#F8F8F8',
move colors to the theme

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/radioButton/styles.ts
> +    borderColor: '#E6E6E6',
move colors to the theme

2024-10-14 10:09 UTC, 02priyanshi commented on src/components/signUpForm/styles.ts
> +export const styles = StyleSheet.create({
same as login form image comment

2024-10-14 10:12 UTC, 02priyanshi requested changes

2024-10-14 10:12 UTC, 02priyanshi commented on src/storage/storage.ts
> +export const clearUserData = async (key: string) => {
it can be and data why name of function is clearUserData

2024-10-14 10:12 UTC, 02priyanshi commented on src/theme/ViewStyles.ts
> +    backgroundColor: 'white',
move colors to the theme

2024-10-15 07:52 UTC, 02priyanshi requested changes

2024-10-15 07:52 UTC, 02priyanshi commented on src/components/baseContainer/BaseContainer.tsx
> +import {SafeAreaView} from 'react-native-safe-area-context';
import from react native

2024-10-15 07:52 UTC, 02priyanshi commented on src/components/loginForm/Loginform.tsx
> +            item.email === loginData.email &&
not a correct way

2024-10-15 07:52 UTC, 02priyanshi commented on src/components/loginForm/Loginform.tsx
> +        onChangeText={(value: string) => handleInputChange('password', value)}
pass prop secureTextEntry for password field

2024-10-15 07:52 UTC, 02priyanshi commented on src/components/loginForm/styles.ts
> +const {width, height} = Dimensions.get('window');
add this in constant file

2024-10-15 07:52 UTC, 02priyanshi commented on src/components/radioButton/RadioButton.tsx
>          {data.map(item => (
use data?.map

2024-10-15 07:52 UTC, 02priyanshi commented on src/components/signUpForm/styles.ts
> +const {width, height} = Dimensions.get('window');
same as loginForm styles

2024-10-15 07:52 UTC, 02priyanshi commented on src/constants/Routes.ts
> +  ADDEVENT: 'ADDEVENT',
maintain uniformity
use _ for seperation

2024-10-15 07:52 UTC, 02priyanshi commented on src/contexts/LoginContext.tsx
>  const userLoginContext = createContext<userLoginContextType | undefined>(
use proper name

2024-10-15 07:52 UTC, 02priyanshi commented on src/types/button.d.ts
>      onPress?: () => void;
onPress can't be optional in button

2024-10-15 07:52 UTC, adiTrivsme commented on src/components/input/Input.tsx
> +      <Text style={[styles.label]}>{label}*</Text>
add prop to mark the field required or not as per need

2024-10-15 07:52 UTC, adiTrivsme commented on src/components/input/Input.tsx
> +        <Text style={styles.invalidLabel}>Please enter correct value</Text>
msg should be dynamic (customizable) as per need

2024-10-15 07:52 UTC, adiTrivsme commented on src/components/loginForm/Loginform.tsx
> +  return (
line break

2024-10-15 07:52 UTC, adiTrivsme commented on src/components/loginForm/styles.ts
> +export const styles = StyleSheet.create({
line break

2024-10-15 07:52 UTC, adiTrivsme commented on src/components/loginForm/styles.ts
> +    color: '#4169E1',
use color from theme

2024-10-15 07:52 UTC, adiTrivsme commented on src/components/signUpForm/SignUpForm.tsx
> +  const emptyForm = {
define this outside the component

2024-10-15 07:52 UTC, adiTrivsme commented on src/contexts/LoginContext.tsx
> +      userId ? setLoginId(userId) : setLoginId('');
can refactor to this - setLoginId(userId || '')

2024-10-15 07:52 UTC, adiTrivsme commented on src/navigation/Navigator.tsx
> +  return <>{!loginId ? <AuthNavigator /> : <TabNavigator />}</>;
`loginId ? <TabNavigator /> : <AuthNavigator />`

why overcomplicating

2024-10-15 07:52 UTC, adiTrivsme commented on src/theme/GlobalStyles.ts
> +    // Add more colors as needed
remove unnecessary comment

2024-10-15 07:52 UTC, adiTrivsme commented on src/theme/GlobalStyles.ts
how come the name is GlobalStyles?

2024-10-15 09:30 UTC, adiTrivsme approved these changes

2024-10-15 09:55 UTC, merged